In [1]:
import json
import pandas as pd  
import numpy as np
from pandas.io.json import json_normalize
import matplotlib.pyplot as plt
%matplotlib inline

In [2]:
tip = pd.read_json('../data/tip.json', lines=True)

In [3]:
tip.shape

(1223094, 5)

In [3]:
tip.axes

[RangeIndex(start=0, stop=1223094, step=1),
 Index(['business_id', 'compliment_count', 'date', 'text', 'user_id'], dtype='object')]

In [4]:
tip.head()

,business_id,compliment_count,date,text,user_id
0,VaKXUpmWTTWDKbpJ3aQdMw,0,2014-03-27 03:51:24,"Great for watching games, ufc, and whatever el...",UPw5DWs_b-e2JRBS-t37Ag
1,OPiPeoJiv92rENwbq76orA,0,2013-05-25 06:00:56,Happy Hour 2-4 daily with 1/2 price drinks and...,Ocha4kZBHb4JK0lOWvE0sg
2,5KheTjYPu1HcQzQFtm4_vw,0,2011-12-26 01:46:17,Good chips and salsa. Loud at times. Good serv...,jRyO2V1pA4CdVVqCIOPc1Q
3,TkoyGi8J7YFjA6SbaRzrxg,0,2014-03-23 21:32:49,The setting and decoration here is amazing. Co...,FuTJWFYm4UKqewaosss1KA
4,AkL6Ous6A1atZejfZXn1Bg,0,2012-10-06 00:19:27,Molly is definately taking a picture with Sant...,LUlKtaM3nXd-E4N4uOk_fQ

In [5]:
sum(tip.groupby('business_id').count()['text'] > 10)

23403

#### Merge with the data only restuarant data for now

In [6]:
main_categories = {'Active Life', 'Arts & Entertainment', 'Automotive', 'Beauty & Spas', 'Bicycles', 'Education', 'Event Planning & Services', 'Financial Services', 'Food', 'Health & Medical', 'Home Services', 'Hotels & Travel', 'Local Flavor', 'Local Services', 'Mass Media', 'Nightlife', 'Pets', 'Professional Services', 'Public Services & Government', 'Religious Organizations', 'Restaurants', 'Shopping'}

In [7]:
business = []
for line in open('../data/business.json', 'r'):
    business.append(json.loads(line))
business = json_normalize(business)

In [8]:
business['categories'] = business['categories'].str.split(", ")
business['categories'] = business['categories'].apply(lambda x: set(np.sort(x)) if x is not None else x)

In [9]:
def resolveToMainCategory(category, main_categories):
    if category is None:
        return None
    main_cat = []
    for cat in category:
        if cat in main_categories:
            main_cat.append(cat)
    main_cat.sort()
    return set(main_cat)

In [10]:
business['main_categories'] = business['categories'].apply(lambda x: resolveToMainCategory(x, main_categories))

In [11]:
def isCategoryInSeries(category, businesses):
    #print (business, businesses)
    if businesses is None:
        return False
    return businesses.issubset(category) 

def findBusinessByCategory(category, df, searchBy):
    return df[searchBy].apply(lambda x : isCategoryInSeries(category, x))

In [12]:
res = findBusinessByCategory({'Restaurants'}, business, 'main_categories')
df = business[res].copy()

In [14]:
merged = pd.merge(tip, df, on='business_id', how='inner')

In [15]:
merged.shape

(402254, 65)

In [16]:
del tip, business, res, df

In [9]:
del tip, review

In [16]:
merged.head()

,business_id,compliment_count,date,text,user_id,address,attributes,attributes.AcceptsInsurance,attributes.AgesAllowed,attributes.Alcohol,...,hours.Wednesday,is_open,latitude,longitude,name,postal_code,review_count,stars,state,main_categories
0,kj1p6NwUGROOoqNySf0I1Q,0,2011-12-31 18:02:42,It's true! The drunken noodles are outrageous!,iAd8XaHxv05iXyEiZ62Ibw,"1805 E Elliot Rd, Ste 115",NaN,NaN,NaN,'beer_and_wine',...,17:0-21:0,1,33.34786,-111.909587,Yupha's Thai Kitchen,85284,638,4.0,AZ,{Restaurants}
1,kj1p6NwUGROOoqNySf0I1Q,0,2011-10-08 22:11:37,By far this is the best Thai restaurant on the...,RAK7ORGqGVrbHZhx-3xyeQ,"1805 E Elliot Rd, Ste 115",NaN,NaN,NaN,'beer_and_wine',...,17:0-21:0,1,33.34786,-111.909587,Yupha's Thai Kitchen,85284,638,4.0,AZ,{Restaurants}
2,kj1p6NwUGROOoqNySf0I1Q,0,2016-04-21 14:48:16,Great food. Great service!,U4TLTCbXB74ageCPDe4Jgw,"1805 E Elliot Rd, Ste 115",NaN,NaN,NaN,'beer_and_wine',...,17:0-21:0,1,33.34786,-111.909587,Yupha's Thai Kitchen,85284,638,4.0,AZ,{Restaurants}
3,kj1p6NwUGROOoqNySf0I1Q,0,2014-05-11 01:01:52,Tom Kha Gai... comfort in a bowl!,zFYs8gSUYDvXkb6O7YkRkw,"1805 E Elliot Rd, Ste 115",NaN,NaN,NaN,'beer_and_wine',...,17:0-21:0,1,33.34786,-111.909587,Yupha's Thai Kitchen,85284,638,4.0,AZ,{Restaurants}
4,kj1p6NwUGROOoqNySf0I1Q,0,2016-04-26 04:29:04,loved the pad garlic Thai and Thai iced coffee...,gZUVSBm-BWntWeQTYH04UQ,"1805 E Elliot Rd, Ste 115",NaN,NaN,NaN,'beer_and_wine',...,17:0-21:0,1,33.34786,-111.909587,Yupha's Thai Kitchen,85284,638,4.0,AZ,{Restaurants}

#### How many resturants have at least 5 tips?

In [17]:
sum(merged.groupby('business_id').count()['text'] > 5)

13096

#### Merge the dataframe with Review information as well

In [18]:
review = pd.read_json('../data/review.json', lines=True)
review.axes

[RangeIndex(start=0, stop=6685900, step=1),
 Index(['business_id', 'cool', 'date', 'funny', 'review_id', 'stars', 'text',
        'useful', 'user_id'],
       dtype='object')]

In [30]:
merged.axes

[Int64Index([     0,      1,      2,      3,      4,      5,      6,      7,
                  8,      9,
             ...
             402244, 402245, 402246, 402247, 402248, 402249, 402250, 402251,
             402252, 402253],
            dtype='int64', length=402254),
 Index(['business_id', 'compliment_count', 'date', 'text', 'user_id',
        'attributes.Alcohol', 'attributes.Ambience', 'attributes.BestNights',
        'attributes.BikeParking', 'attributes.BusinessAcceptsCreditCards',
        'attributes.BusinessParking', 'attributes.Caters',
        'attributes.CoatCheck', 'attributes.Corkage',
        'attributes.DietaryRestrictions', 'attributes.DogsAllowed',
        'attributes.DriveThru', 'attributes.GoodForDancing',
        'attributes.HairSpecializesIn', 'attributes.Open24Hours',
        'attributes.RestaurantsCounterService', 'attributes.Smoking',
        'categories', 'city', 'is_open', 'latitude', 'longitude', 'name',
        'postal_code', 'review_count', 'stars', 'state'],
       dtype='object')]

In [25]:
merged = merged.drop(['address', 'hours', 'hours.Friday',
        'hours.Monday', 'hours.Saturday', 'hours.Sunday', 'hours.Thursday',
        'hours.Tuesday', 'hours.Wednesday', 'main_categories', 'attributes'], axis = 1)

In [28]:
merged = merged.drop(['attributes.AcceptsInsurance', 'attributes.AgesAllowed', 'attributes.BYOB',
        'attributes.BYOBCorkage', 'attributes.BusinessAcceptsBitcoin',  'attributes.ByAppointmentOnly',
        'attributes.GoodForKids', 'attributes.GoodForMeal',
        'attributes.HappyHour', 'attributes.HasTV', 'attributes.Music', 'attributes.NoiseLevel',
        'attributes.OutdoorSeating', 'attributes.RestaurantsAttire', 
        'attributes.RestaurantsDelivery', 'attributes.RestaurantsGoodForGroups',
        'attributes.RestaurantsPriceRange2',
        'attributes.RestaurantsReservations',
        'attributes.RestaurantsTableService', 'attributes.RestaurantsTakeOut',
        'attributes.WheelchairAccessible',
        'attributes.WiFi'], axis = 1)

In [31]:
merged = merged.drop(['attributes.Alcohol', 'attributes.Ambience', 'attributes.BestNights',
        'attributes.BikeParking', 'attributes.BusinessAcceptsCreditCards',
        'attributes.BusinessParking', 'attributes.Caters',
        'attributes.CoatCheck', 'attributes.Corkage',
        'attributes.DietaryRestrictions', 'attributes.DogsAllowed',
        'attributes.DriveThru', 'attributes.GoodForDancing',
        'attributes.HairSpecializesIn', 'attributes.Open24Hours',
        'attributes.RestaurantsCounterService', 'attributes.Smoking',
        'categories', 'city', 'is_open', 'latitude', 'longitude', 'name',
        'postal_code', 'review_count', 'stars', 'state'], axis = 1)

In [ ]:
review.axes

In [32]:
merged = pd.merge(merged, review, on='business_id', how='inner')

In [33]:
del review

In [34]:
merged.axes

[Int64Index([        0,         1,         2,         3,         4,         5,
                     6,         7,         8,         9,
             ...
             176990607, 176990608, 176990609, 176990610, 176990611, 176990612,
             176990613, 176990614, 176990615, 176990616],
            dtype='int64', length=176990617),
 Index(['business_id', 'compliment_count', 'date_x', 'text_x', 'user_id_x',
        'cool', 'date_y', 'funny', 'review_id', 'stars', 'text_y', 'useful',
        'user_id_y'],
       dtype='object')]

In [26]:
merged.axes

[Int64Index([     0,      1,      2,      3,      4,      5,      6,      7,
                  8,      9,
             ...
             402244, 402245, 402246, 402247, 402248, 402249, 402250, 402251,
             402252, 402253],
            dtype='int64', length=402254),
 Index(['business_id', 'compliment_count', 'date', 'text', 'user_id', 'address',
        'attributes', 'attributes.AcceptsInsurance', 'attributes.AgesAllowed',
        'attributes.Alcohol', 'attributes.Ambience', 'attributes.BYOB',
        'attributes.BYOBCorkage', 'attributes.BestNights',
        'attributes.BikeParking', 'attributes.BusinessAcceptsBitcoin',
        'attributes.BusinessAcceptsCreditCards', 'attributes.BusinessParking',
        'attributes.ByAppointmentOnly', 'attributes.Caters',
        'attributes.CoatCheck', 'attributes.Corkage',
        'attributes.DietaryRestrictions', 'attributes.DogsAllowed',
        'attributes.DriveThru', 'attributes.GoodForDancing',
        'attributes.GoodForKids', 'attributes.GoodForMeal',
        'attributes.HairSpecializesIn', 'attributes.HappyHour',
        'attributes.HasTV', 'attributes.Music', 'attributes.NoiseLevel',
        'attributes.Open24Hours', 'attributes.OutdoorSeating',
        'attributes.RestaurantsAttire', 'attributes.RestaurantsCounterService',
        'attributes.RestaurantsDelivery', 'attributes.RestaurantsGoodForGroups',
        'attributes.RestaurantsPriceRange2',
        'attributes.RestaurantsReservations',
        'attributes.RestaurantsTableService', 'attributes.RestaurantsTakeOut',
        'attributes.Smoking', 'attributes.WheelchairAccessible',
        'attributes.WiFi', 'categories', 'city', 'hours', 'hours.Friday',
        'hours.Monday', 'hours.Saturday', 'hours.Sunday', 'hours.Thursday',
        'hours.Tuesday', 'hours.Wednesday', 'is_open', 'latitude', 'longitude',
        'name', 'postal_code', 'review_count', 'stars', 'state',
        'main_categories'],
       dtype='object')]

In [31]:
del review

In [37]:
merged.axes

[Int64Index([        0,         1,         2,         3,         4,         5,
                     6,         7,         8,         9,
             ...
             176990607, 176990608, 176990609, 176990610, 176990611, 176990612,
             176990613, 176990614, 176990615, 176990616],
            dtype='int64', length=176990617),
 Index(['business_id', 'compliment_count', 'date_x', 'text_x', 'user_id_x',
        'cool', 'date_y', 'funny', 'review_id', 'stars', 'text_y', 'useful',
        'user_id_y'],
       dtype='object')]

In [40]:
review.shape()

NameError: name 'review' is not defined

In [39]:
merged.head()

,business_id,compliment_count,date_x,text_x,user_id_x,cool,date_y,funny,review_id,stars,text_y,useful,user_id_y
0,kj1p6NwUGROOoqNySf0I1Q,0,2011-12-31 18:02:42,It's true! The drunken noodles are outrageous!,iAd8XaHxv05iXyEiZ62Ibw,0,2017-05-13 04:34:24,0,7mF_zkgTU9v3JR2A5HuGXA,1,Food is great thats why I go there . A friend ...,2,LXj5ldLyrGu3u6dDRJRGJQ
1,kj1p6NwUGROOoqNySf0I1Q,0,2011-12-31 18:02:42,It's true! The drunken noodles are outrageous!,iAd8XaHxv05iXyEiZ62Ibw,0,2013-12-07 02:50:44,0,DGj2CGS98ZDZu0SOf0GiLw,5,I think this place is often overlooked. The dr...,0,O4XcYj0AeaGAaAb6ifL5aQ
2,kj1p6NwUGROOoqNySf0I1Q,0,2011-12-31 18:02:42,It's true! The drunken noodles are outrageous!,iAd8XaHxv05iXyEiZ62Ibw,0,2010-03-13 00:19:25,0,J1dksQEa1RqzuC89Hn10DA,2,I thought the service was good and it is a ver...,0,h-hL-W5LEekosgzvWPG6qQ
3,kj1p6NwUGROOoqNySf0I1Q,0,2011-12-31 18:02:42,It's true! The drunken noodles are outrageous!,iAd8XaHxv05iXyEiZ62Ibw,0,2015-05-12 18:11:02,0,dA7wO_17G6iCC60WITTLsQ,5,Best Thai food in the valley! Gets very busy a...,1,7p1FfxnjZAuNydjLKEW_Yg
4,kj1p6NwUGROOoqNySf0I1Q,0,2011-12-31 18:02:42,It's true! The drunken noodles are outrageous!,iAd8XaHxv05iXyEiZ62Ibw,2,2013-02-21 22:42:32,0,QH08mTSAzPG85owSRMCZHw,4,It's been awhile since my last update and I wi...,3,rhE4gLtM0gb3XLwSz6HPCw

In [36]:
sum(merged.groupby('business_id').count()['text_x'] > 5)

MemoryError:

In [36]:
merged[['text', 'business_id', 'user_id']]

,text,business_id,user_id
0,It's true! The drunken noodles are outrageous!,kj1p6NwUGROOoqNySf0I1Q,iAd8XaHxv05iXyEiZ62Ibw
1,By far this is the best Thai restaurant on the...,kj1p6NwUGROOoqNySf0I1Q,RAK7ORGqGVrbHZhx-3xyeQ
2,Great food. Great service!,kj1p6NwUGROOoqNySf0I1Q,U4TLTCbXB74ageCPDe4Jgw
3,Tom Kha Gai... comfort in a bowl!,kj1p6NwUGROOoqNySf0I1Q,zFYs8gSUYDvXkb6O7YkRkw
4,loved the pad garlic Thai and Thai iced coffee...,kj1p6NwUGROOoqNySf0I1Q,gZUVSBm-BWntWeQTYH04UQ
5,The address is wrong on this restaurant so it'...,kj1p6NwUGROOoqNySf0I1Q,mCcpEWdwOo3Ri82zn34MmA
6,Thai fried rice w tofu is great for this veget...,kj1p6NwUGROOoqNySf0I1Q,AfWfOF4qwJcVn8By_PKf2A
7,I'll review later but the red curry level of s...,kj1p6NwUGROOoqNySf0I1Q,U6beJJmfvDcPc-ry8vpeQA
8,Great food but not happy with the fox price in...,kj1p6NwUGROOoqNySf0I1Q,WPEZrwh_2qkzxCl9CMswIg
9,The pad Thai tastes fishy but the veg fried ri...,kj1p6NwUGROOoqNySf0I1Q,buye5-su0QSkcRaSiXAQdw
10,One of my fave Thai restaurants to go to!! Go ...,kj1p6NwUGROOoqNySf0I1Q,-KzQH0n2ryLorsVgO7KeRw
11,Great service and atmosphere and the food is a...,kj1p6NwUGROOoqNySf0I1Q,GujmIug5D5aXZ0WTfiRISg
12,Don't come in at 2:30 pm because they ACTUALLY...,kj1p6NwUGROOoqNySf0I1Q,2eToXGVa0Fzti8drf3HaoQ
13,Excellent yesterday. Came back for more.,kj1p6NwUGROOoqNySf0I1Q,fuCsHvb-JyKnUbvV-040lQ
14,Best Thai in Tempe.,kj1p6NwUGROOoqNySf0I1Q,E6mfSwfPb7Tfkd9_TSGY0w
15,"Wow, red curry with pumpkin is so yummy",kj1p6NwUGROOoqNySf0I1Q,Gl9XFtwFgIifENxZKqRSfA
16,Trying this for the first time. Wait for the o...,kj1p6NwUGROOoqNySf0I1Q,AY2SFB2138n4srDPruCYow
17,Animal cruelty free soap in their bathroom!,kj1p6NwUGROOoqNySf0I1Q,xceJT1G2Yhel3W2lRxRTDA
18,Oh em gee. Most Thai places say thai hot and i...,kj1p6NwUGROOoqNySf0I1Q,unY-F7AsYkQDvILMpd3jPw
19,I love Yupha's I come here regularly. The wait...,kj1p6NwUGROOoqNySf0I1Q,tOzylErjY0jP-pULRgBLjQ
20,My go to for Thai food! Always great food and...,kj1p6NwUGROOoqNySf0I1Q,g9KzKQHuHfUE85nnUPCKfA
21,First time!,kj1p6NwUGROOoqNySf0I1Q,35MI_KUO4L_fKb8mAVFwng
22,Great place for fried rice! My favorite is the...,kj1p6NwUGROOoqNySf0I1Q,McHkH_RESr5-9jpngXbCdA
23,My favorite place for Thai food! Generous port...,kj1p6NwUGROOoqNySf0I1Q,oBk4GKgqW8fpJ7nfOEJ8xA
24,"Dude, what happened? Double Thai Hot was more ...",kj1p6NwUGROOoqNySf0I1Q,eA8WqJj_15lWURDwE6DsKQ
25,Drunken noodles = yum yum!,kj1p6NwUGROOoqNySf0I1Q,puQZ4-PygUlfrggcbVeL8w
26,Thai hot,kj1p6NwUGROOoqNySf0I1Q,qWdQo-s7zAOwLS9W0MxTgg
27,Best chicken in red curry-med spice. Awesome d...,kj1p6NwUGROOoqNySf0I1Q,5VxUSNMXRYWPMPB0ely63g
28,Drunken noodle pork is phenomenal!,kj1p6NwUGROOoqNySf0I1Q,4Tg4Z1fnt10vLHQScRfDnA
29,"Chicken Pad Thai enough for three meals, glass...",kj1p6NwUGROOoqNySf0I1Q,eA8WqJj_15lWURDwE6DsKQ
...,...,...,...
402224,no one is gonna answer the phone,CdWDUfMuN5PDcFHtr9Wvyg,bWDgZVfUr2N7fvbefueSAA
402225,"Authentic Spanish food, great Sangria and tapas!",-1u4Q4U6OZ-CvqoxUh7gKg,0XFztFPJpCFxyMvfvLuQwQ
402226,Worst food ever! OMG can't imagine how bad it is.,ckc3l8cSuggloG4NlquEFQ,cYEaBtzokEehtRdfaFjEgQ
402227,La poutine est délicieuse!!,vFvREHydOVYEJ-AlrkcG5g,UdmUYArGgKy6chin_OQ32Q
402228,Perfect breakfast and nice service. Pot of cof...,NylJ-RKjerzp3PfRqWvu5A,DyFO03BVu1wwqDQZEcapyQ
402229,Really outstanding Italian food. Easy 5 star.,Q2OjPFhDg_5JqzXmWChpZw,mOqp82VDoX4WPk2cPyzDyQ
402230,Best fried chicken wings ever! Must have with ...,XOMZyF__Wnm0GHhb1uHw6w,63xgDbVKAwsOPMrgBSiP7g
402231,"Food was good, price was good and fast service",M5rnBQaFtjYTn3T9NIZwcA,U1GTUg6YgYIb-UBNCvwqIA
402232,Horrible,Y3FcorCGv0U-ecprHT1Hxg,VZbUol12fe3JSqdxyrywJQ
402233,Good mojitos!,rtcHe089qa8hjtlO_en4-Q,YGjKpSrX0SZO6PV4lcaSZw
402234,Wings!,Mg7AbrKjARuHBaixSk1AqA,pzwY9n_EpJtdmLoE9DBYDg
402235,Disgusting food at it's best,7um-gnjmA5sqnUcM9Gh2Mg,gZZVfKDd6LsGSgjiyuh2KQ
402236,Solid take out chicken for the price. Hot sauc...,St6h2WGJBSktsgW_x-piIQ,fjbv_NiVLWgvZzTvLuG1MQ
402237,Delicious.FriendlyService.,FsgF4JBv56pNpOT-2kAy8Q,cdSMV92HU-FbaUmrGtfJYw
402238,Best pulled Pork sandwich I've ever had!,Amx-KvDm_9nemssJM_X_Fg,Drj-LrDq0ESzMI7-U5pGXg
402239,Great food with friendly service! Will be comi...,5Bg9DcM28EUbPRffR8VECw,P4mrkEIFp90aqDzuX9hHTw
402240,We love you Sherry.,XE97VxjZoRxV6IM05grY0g,7DTnDEZv1gRGM01fxbp4tg
402241,Great Hummus!,de_wsnOXf4mVVd4jlISmFg,LVVNpjXYWNe02Rd8_x9SQw
402242,Worst service ever!!!,rNrGT18rg8wctucG8bIGTw,1y4A8XeG4ryxiG1aJAI56A
402243,"Food was ok, service slow and not very friendl...",JLMY9LH1K1X9GkCJqWCGmA,1QndqLcu_X_5zMwXk6o4Dg
402244,Under new management! Love this place! Reasona...,XUdWc5vRG4z6qauPtN47TA,FQCYKNr-KD9FaQEjo9ApzQ
402245,Best food in town. Also halal,9Cqh3vLTKTjZkoF03Udrtw,fuFz3lR_v3wNeb5sLI1e5A
402246,Polish boy is amazing it's massive,3Jx9x7QTbrzXcigublX6RA,VeTg_OzN795l13v2Q1zw5g
402247,Get $1.35 off a regular combo with your I-card...,RwMlwusAtxZc5a3ZYduulg,47k48YYihyXZ101XC57Aow
402248,Our family went here and really enjoyed our me...,J2yHV9KNwBHD7bnGMANCpw,C52j3UfKcQ2ncjuf950a4w
402249,Food was good but their sushi needs work... sh...,N3ZbTZfWC_oyIUxuX9KJYA,x1N0ytaGRjNqd1woPSk4zA
402250,Terrible attitude. Stay away,uqPHO-o4stxGXLdxP3WNig,LfgRW5Wq_WxD_hl6NQjdFw
402251,Best wiener a gal could ask for,xE4WM5ZvtBkFnojFUTQfqg,2noSA01c_6217Q_quNQ8RQ
402252,...then to the art fest!,P2l7s26bzzN_QgkWSVg3sw,TO4FGXDJmIDk-sFFntff8A
402253,"Nice food, good service, when it's busy, you m...",caxSO8gwOWMtNTZulDwyUw,MnDytBBXTTsE20YoRk_OKg